---
kind: pipeline
name: go-1-11

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags

  - name: test
    image: golang:1.11
    environment:
      COVERALLS_TOKEN:
        from_secret: coveralls_token
    volumes:
      - name: deps
        path: /go
    commands:
      - make coveralls

  - name: lint
    image: golang:1.11
    volumes:
      - name: deps
        path: /go
    commands:
      - make lint

  - name: build
    image: golang:1.11
    volumes:
      - name: deps
        path: /go
    commands:
      - make build

  - name: release
    image: golang
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: deps
        path: /go
    commands:
      - make release
    when:
      event:
      - tag

volumes:
  - name: deps
    temp: {}

---
kind: signature
hmac: b97804e2fed0c345dfc0d5fef594cce9c239e9adeb8f0d111786d5522c45b7e6

...
