---
kind: pipeline
name: go-1-11

steps:
  - name: test-lint-build
    image: golang:1.11
    volumes:
      - name: deps
        path: /go
    commands:
      - make test COVERAGE_FILE=coverage.txt
      - make lint
      - make build

  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov_token
    files:
     - coverage.txt

volumes:
  - name: deps
    temp: {}

---
kind: pipeline
name: release

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags

  - name: release
    image: golang
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - make release
    when:
      event:
        - tag

depends_on:
  - go-1-11
---
kind: signature
hmac: bbc61b59d485cd4beae86c9be0adaf2897a66e40b02c8118726c19490dfac68c

...
