---
kind: pipeline
name: go-1-11

steps:
  - name: test-lint-build
    image: golang:1.11
    volumes:
      - name: deps
        path: /go
    commands:
      - make test
      - make lint
      - make build

  - name: coverage
    image: golang:1.11
    environment:
      CODECOV_TOKEN:
        from_secret: codecov_token
    volumes:
      - name: deps
        path: /go
    commands:
      - make codecov

volumes:
  - name: deps
    temp: {}

---
kind: pipeline
name: release

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags

  - name: release
    image: golang
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - make release
    when:
      event:
        - tag

---
kind: signature
hmac: b97804e2fed0c345dfc0d5fef594cce9c239e9adeb8f0d111786d5522c45b7e6

...
