---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: test-build
  image: golang:1.13
  commands:
  - make test
  - make build

trigger:
  branch:
    exclude:
    - master

---
kind: pipeline
name: test-master-go-1-13

platform:
  os: linux
  arch: amd64

steps:
- name: test-build
  image: golang:1.13
  commands:
  - make test COVERAGE_FILE=coverage.txt
  - make build
  volumes:
  - name: deps
    path: /go

- name: lint
  image: golang:1.13
  commands:
  - make lint
  volumes:
  - name: deps
    path: /go

- name: coverage
  image: plugins/codecov
  settings:
    required: true
    token:
      from_secret: codecov_token

volumes:
- name: deps
  temp: {}

trigger:
  branch:
  - master

---
kind: pipeline
name: test-master-go-1-12

platform:
  os: linux
  arch: amd64

steps:
- name: test-build
  image: golang:1.12
  commands:
  - make test
  - make build

trigger:
  branch:
  - master

---
kind: pipeline
name: release

platform:
  os: linux
  arch: amd64

steps:
- name: fetch
  image: docker:git
  commands:
  - git fetch --tags

- name: release
  image: golang:1.13
  commands:
  - make release
  environment:
    GITHUB_TOKEN:
      from_secret: github_token

trigger:
  event:
  - tag

---
kind: signature
hmac: cda23a221a730cd62ef0bf7a9885206085d42654c088eceda87725ddf0162af8

...
