package config

// Config represents the content of the configuration file.
// It defines the schema for Marshal and Unmarshal the data of the configuration file.
type Config struct {
	// APIAppCredentials represents Google Photos API credentials for OAuth.
	APIAppCredentials APIAppCredentials `json:"APIAppCredentials"`

	// Account is the Google Photos account to work with.
	Account string `json:"Account"`

	// SecretsBackendType is the type of backend to store secrets.
	SecretsBackendType string `json:"SecretsBackendType"`

	// Jobs are the source folders to work with.
	Jobs []FolderUploadJob `json:"Jobs"`
}

// APIAppCredentials represents Google Photos API credentials for OAuth.
type APIAppCredentials struct {
	// ClientID is the app identifier generated on the Google API console.
	ClientID string `json:"ClientID"`
	// ClientSecret is the secret key generated on the Google API console.
	ClientSecret string `json:"ClientSecret"`
}

// FolderUploadJob represents configuration for a folder to be uploaded
type FolderUploadJob struct {
	// SourceFolder is the folder containing the objects to be uploaded.
	SourceFolder string `json:"SourceFolder"`

	// Album is the album where objects will be uploaded.
	// If the Album option is not set, the objects will not be associated with an album in Google Photos.
	//
	// These are the valid values: "name:" and "auto:".
	//   "name:" : Followed by the album name in Google Photos (album names are not unique, so the first to match
	//             will be selected)
	//   "auto:" : Followed either "folderPath" or "folderName" will use an autogenerated album name based on the
	//             object's folder path or object's folder name.
	Album string `json:"Album,omitempty"`

	// CreateAlbums is the parameter to create albums on Google Photos.
	//
	// Deprecated: CreateAlbums exists to maintain backwards compatibility with version 4.x. It should not be used in
	// favor of the Album option.
	//
	// Valid options were:
	// Off: Disable album creation (default).
	// folderPath: Creates album with the name based on full folder path.
	// folderName: Creates album with the name based on the folder name.
	CreateAlbums string `json:"CreateAlbums,omitempty"`

	// DeleteAfterUpload if it is true, the app will remove files after upload them.
	DeleteAfterUpload bool `json:"DeleteAfterUpload"`

	// IncludePatterns are the patterns to include files to work with.
	IncludePatterns []string `json:"IncludePatterns"`

	// ExcludePatterns are the patterns to exclude files.
	ExcludePatterns []string `json:"ExcludePatterns"`
}
