on: [push]

name: Test Push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: make test
      - name: Send code coverage
        uses: codecov/codecov-action@v1